language: node_js

node_js:
  - v7

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.electron

script:
  - npm run lint

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then npm run build:app && npm run package; fi;

deploy:
  provider: releases
  api_key:
    secure: iBdhN0QKgOHKgfZc3bfXr0qzFe0QdG0LGGoeJkcbe4HfWHcXIJpEQFzRMbMy2208uQlRKUflScC3hKtqThrKuv8IKZwCVTEsjH4gIhP9W1EVPJAoVOj0/kTo3QVJA3eP3tjxzLfHRzj1iJXmDm9QOKgBYadSwbX3aUpSWlKGszWG0d4Eszk3x5eN0oDcoRH28JJ8YYlJlm8I+LFj26Up98Zkn8INMU2XgGG7N8QpWAEAwHIv7mA6Zc06NTutIsPa9us1vH/6biraBm/KyfLTLUVsV5WLD6GBDG+0tZY0vXT1HRDIWOyIaMUQ3QK+0VjdTs1Ac7N8//jhcNWHLNVB0aJ9jYSh9j1K6CLGPoNjr4lJROkwYr0IgYEH6XkjeQM4i05YqBDAJR2UOIrrlhHvUV7BcYkHV1CClpMxGmcXRV+/QPablN0izFHunMmetioYmvbMCdLb3MveLEdzRJeOJDT6qhXolTPfOrDGb3cm48MfWKHTH3lXZMQnMntfCJQ8aEcW4upnKd3nSGkVbYKwb1fCNS3TuirYE/AHHPq4eGYSDDONhqBCPkO6aQtJFb9Qh57esUJ5oMWNSlm4SxVubYGEPUWdd6u1okylQ2i3aVOsWxy3C3QPyyNhQupW0Ca8p1qdOPJbIk4xjAM5uPTgy+to5EkTo65DpCvBdNGWR70=
  file_glob: true
  file: dist/*.tar.bz2
  skip_cleanup: true
  on:
    tags: true
