#!/usr/bin/env sh

TMP_DIR=$(mktemp -d)
GH_REPO=github.com/${TRAVIS_REPO_SLUG}

# clone gh-pages branch
git clone --branch gh-pages git://${GH_REPO} ${TMP_DIR}

# create archives
cd ./dist
for dir in *
do
  if [ -n "$TRAVIS_TAG" ]; then
    rm -rf ${TMP_DIR}/downloads/${dir}-latest.tar.bz2
    rm -rf ${TMP_DIR}/downloads/${dir}-${TRAVIS_TAG}.tar.bz2

    tar -cjf ${TMP_DIR}/downloads/${dir}-${TRAVIS_TAG}.tar.bz2 ${dir}
    cp ${TMP_DIR}/downloads/${dir}-${TRAVIS_TAG}.tar.bz2 ${TMP_DIR}/downloads/${dir}-latest.tar.bz2
  fi

  rm -rf ${TMP_DIR}/downloads/${dir}-dev.tar.bz2
  tar -cjf ${TMP_DIR}/downloads/${dir}-dev.tar.bz2 ${dir}
done

# commit and push changes
cd ${TMP_DIR}
git config user.name "Travis CI"
git config user.email "build@travis-ci.org"
git add -A .
if [ -n "$TRAVIS_TAG" ]; then
  git commit -m "Build ${TRAVIS_TAG}"
else
  git commit -m "Built from ${TRAVIS_COMMIT}"
fi
git push -q "https://${GH_TOKEN}@${GH_REPO}" gh-pages > /dev/null 2>&1
