#!/usr/bin/env sh

rm -rf ./dist/*

electron-packager ./build \
  --platform darwin \
  --arch x64 \
  --out ./dist \
  --icon ./build/electron/CoffeeWriter.icns \
  --asar

cd ./dist

for dir in *
do
  tar -cjf ${dir}-${TRAVIS_TAG}.tar.bz2 ${dir}
done
