#!/usr/bin/env sh

rm -rf ./dist/*

electron-packager ./build \
  --platform darwin \
  --arch x64 \
  --out ./dist \
  --icon ./build/electron/CoffeeWriter.icns \
  --asar

for dir in $(find ./dist -type d -maxdepth 1)
do
    package=$(basename $dir)

    tar -C ${dir} -cjf ./dist/${package}-${TRAVIS_TAG}.tar.bz2 .
done
